config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'events' => 'event#aggregates'
  post 'event'  => 'event#create'
  get '/research/events'  => 'event#index'
  get '/research/events/export' => 'event#export'

  get 'inform' => 'home#inform'
  get 'hazard' => 'home#hazard'

  get 'influenza' => 'home#influenza'
  get 'denguefever' => 'home#dengue'
  get 'project' => 'home#project'
  get 'contact' => 'home#contact'
  get 'disclaimer' => 'home#disclaimer'
  get 'faq' => 'home#faq'

  root to: 'home#index'

end

app/models/aggregate.rb
class Aggregate < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :ip, presence: true

  validates :gender, inclusion: { in: ['male', 'female'] }, allow_nil: true
  validates :age, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :confirmable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :expose_agent
  before_action :set_locale

  def expose_agent
    @agent = request.user_agent
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def self.redis
    @@redis ||= Redis.new
  end

  def redis
    self.redis
  end

  def default_url_options(opt = {})
    logger.debug "default_url_options ignores: #{opt.inspect}"
    { locale: I18n.locale }
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController

  before_action :authenticate_user!, except: [:create, :aggregates]

  def create
    logger.info params
    e = Event.new

    # Required
    e.ip = request.ip.to_s
    e.longitude = params[:lon]
    e.latitude  = params[:lat]
    e.event_type = params[:disease]

    # Optional
    e.gender = params[:gender] unless params[:gender].blank?
    begin
      e.age = params[:age].to_i unless params[:age].blank?
    rescue => ex
      logger.error ex.inspect
      # Ignored
    end
    e.event_subtype = params[:disease_type] unless params[:disease_type].blank?

    unless e.save
      logger.warn("Failed to create event with: params=#{params.inspect}, IP=#{request.ip}, err=#{e.errors.inspect}")
    end
    respond_to do |format|
      format.html { redirect_to redirect_target(e.event_type) }
      format.json { render json: {}, status: :ok }
    end
  end

  # PRIVATE, detailed data for the project research.
  # GET /events.json
  def index
    @events = Event.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @events.collect{|e|
        {
          disease: e.event_type,
          type: e.event_subtype,
          lat: e.latitude,
          lon: e.longitude,
          gender: e.gender,
          age: e.age,
          weight: 1
        }
      }, status: :ok }
    end
  end

  # PRIVATE
  def export
    @events = Event.all
    respond_to do |format|
      format.csv { render_csv "events-#{Time.now}" }
      format.json { render json: @events.collect{|e|
        {
          disease: e.event_type,
          type: e.event_subtype,
          lat: e.latitude,
          lon: e.longitude,
          gender: e.gender,
          age: e.age,
          weight: 1
        }
      }, status: :ok, template: :index }
    end
  end

  # PUBLIC, aggregated data for privacy protection.
  # GET /events.json
  def aggregates
    @events = Aggregate.all
    respond_to do |format|
      format.json { render json: @events.collect{|e|
        {
          disease: e.disease,
          lat: e.latitude,
          lon: e.longitude,
          weight: e.weight,
        }
      }, status: :ok }
    end
  end

  private
  def redirect_target(event)
    case event
    when 'influenza' then :influenza
    when 'dengue' then :denguefever
    else :root
    end
  end

  def render_csv(filename = nil)
    filename ||= 'data'
    filename += '.csv'

    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain"
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      headers['Expires'] = "0"
    else
      headers["Content-Type"] ||= 'text/csv'
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
    end

    render layout: false
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def inform
  end

  def hazard
  end

  def project
  end

  def influenza
  end

  def dengue
  end

  def contact
  end

  def disclaimer
  end

  def faq
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/event/export.csv.haml
Disease, Type, Latitude, Longitude, Gender, Age
= CSV.generate do |csv|
  - @events.each do |e|
    - csv << [e.event_type, e.event_subtype, e.latitude, e.longitude, e.gender || '', e.age || '']

app/views/event/index.html.haml
%div
  %ul{class: 'action-menu'}
    %li
      = link_to 'Export to CSV', controller: :event, action: :export, format: :csv

%hr

%table
  %thead
    %tr
      %th= I18n.t('events.disease')
      %th= I18n.t('events.type')
      %th= I18n.t('events.longitude')
      %th= I18n.t('events.latitude')
      %th= I18n.t('events.gender')
      %th= I18n.t('events.age')
      %th= I18n.t('events.timezone')
  %tbody
    - @events.each do |e|
      %tr
        %td= e.event_type
        %td= e.event_subtype
        %td= e.longitude
        %td= e.latitude
        %td= e.gender
        %td= e.age
        %td= e.created_at.strftime('%Y-%m-%d %H:%M:%S')

app/views/home/contact.html.haml
%h1
  = I18n.t('contact.title')

app/views/home/dengue.html.haml
%h1
  = I18n.t 'dengue.title'

%p
  = I18n.t 'dengue.part1'

%p
  = I18n.t 'dengue.part2'

app/views/home/disclaimer.html.haml
%h1
  = I18n.t('disclaimer.title')

app/views/home/faq.html.haml
%h1
  = I18n.t('faq.title')

%p
  TODO

app/views/home/hazard.html.haml
%div{class: :waiting, id: :waiting}
  = I18n.t('hazard.search_location')
%div{id: 'map-canvas'}

app/views/home/index.html.haml
%table{class: :mosaic}
  %tr
    %td
    %td{class: 'light-red'}
      = link_to I18n.t('navigation.project'), project_path
    %td
  %tr
    %td{class: 'red'}
      = link_to I18n.t('navigation.influenza'), influenza_path
    %td{class: 'dark-red'}
      = image_tag 'logo.png', width: '274px', height: '61px', alt: 'Infection Map', title: 'Infection Map'
    %td{class: 'red'}
      = link_to I18n.t('navigation.dengue'), denguefever_path
  %tr
    %td
    %td{class: 'light-red'}
      = link_to I18n.t('navigation.faq'), faq_path
    %td

app/views/home/influenza.html.haml
:javascript
  var map = new crowdy.map;
  $(document).ready(map.setup);
  $(window).load(map.setup);

%h1
  = I18n.t 'influenza.title'

%div{class: :waiting, id: :waiting}
  = I18n.t('hazard.search_location')
%div{id: 'map-canvas'}

%p
  = I18n.t 'influenza.part1'

%p
  = I18n.t 'influenza.part2'

app/views/home/inform.html.haml
:javascript
  var setup = function() {
    var disease = document.querySelector('#disease');
    if (disease) {
      disease.onchange = function (selection) {
        var dtype = document.querySelector('#disease_type');
        if (!dtype) { return; };
        if (selection.target.value == "influenza") {
          $(dtype).prop("disabled", false);
        } else {
          $(dtype).prop("disabled", true);
        }
      };
    }

    var msgPack = {
      "confirm": "Do you confirm the disease?",
      "button": "Inform"
    };
    if (document.URL.match("locale=jp")) {
      msgPack = {
        "confirm": "本当に？お大事に…",
        "button": "申告"
      };
    } else if (document.URL.match("locale=fr")) {
      msgPack = {
        "confirm": "Confirmez-vous la contraction?",
        "button": "Enregistrer"
      };
    }
    var button = document.querySelector('#button');
    if (button) {
      button.onclick = function () { return confirm(msgPack.confirm); };
    }

    var setPosition = function(latitude, longitude) {
        var lat = document.querySelector("#latitude");
        var lon = document.querySelector("#longitude");
        if (21 < latitude && latitude < 49
          && 121 < longitude && longitude < 149) {
          if (lat)
            lat.value = latitude;
          if (lon)
            lon.value = longitude;
        } else {
          if (lat)
            lat.value = 35.632291;
          if (lon)
            lon.value = 139.881371;
        }
        if (lat.value != '' && lon.value != '') {
          $(button).removeAttr("disabled");
          button.value = msgPack.button;
        }
    };

    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        setPosition(position.coords.latitude, position.coords.longitude);
      });
    } else {
      setPosition(crowdy.map.defaultLat, crowdy.map.defaultLon);
    }
  };

  $(document).ready(setup);
  $(document).load(setup);

%p
  = I18n.t('inform.explanation')

%form{action: 'event', method: :post}
  %p
    %label{for: :disease}
      = I18n.t 'inform.disease'
    %select{id: :disease, name: :disease}
      %option{value: :influenza}
        = I18n.t 'disease.influenza'
      %option{value: :dengue}
        = I18n.t 'disease.dengue'
  %p
    %label{for: :gender}
      = I18n.t 'inform.gender'
    %select{name: :gender}
      %option{value: ""}
        = ""
      %option{value: :male}
        = I18n.t 'inform.male'
      %option{value: :female}
        = I18n.t 'inform.female'
  %p
    %label{for: :age}
      = I18n.t 'inform.age'
    %input{type: :number, name: :age, id: :age, step: 1, min: 0}
  %p
    %label{for: :disease_type}
      = I18n.t 'inform.type'
    %select{id: :disease_type, name: :disease_type}
      %option{value: ""}
        = ""
      %option{value: :a}
        = I18n.t 'inform.a'
      %option{value: :b}
        = I18n.t 'inform.b'
      %option{value: :other}
        = I18n.t 'inform.other'
  %input{type: :hidden, name: :locale, value: I18n.locale}
  %input{type: :hidden, name: :lat, value: '', id: :latitude}
  %input{type: :hidden, name: :lon, value: '', id: :longitude}
  %input{type: :submit, value: I18n.t('inform.search_location'), id: 'button', disabled: true}

%p
  = I18n.t('inform.thanks')

app/views/home/project.html.haml
%h1
  = I18n.t('project.title')

%p
  = I18n.t('project.part1')

%p
  = I18n.t('project.part2')

%p
  = I18n.t('project.part3')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Infection Map
    %meta{charset: 'utf-8'}
    %meta{name: :viewport, content: "initial-scale=1.0, user-scalable=no"}
    - if @agent =~ /iPhone/
      %meta{name: 'apple-mobile-web-app-capable', content: :yes}
    - elsif @agent =~ /iPhone/ or @agent =~ /Android/
      %meta{name: :viewport, content: "user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{type: 'text/javascript', src: "https://maps.googleapis.com/maps/api/js?libraries=visualization&key=AIzaSyAO_gjNW54LtbRI1bAFaD52L0hEBijbRpE&sensor=true"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div{id: 'container'}
      %div{id: 'header'}
        %div{id: 'logo'}
          %a{href: root_path}
            = image_tag 'logo.png', width: '274px', height: '61px', alt: 'Infection Map', title: 'Infection Map'
        %div{id: 'submitbutton'}
          %a{href: inform_path}
            = image_tag 'button.png', width: '56px', height: '57px', alt: 'Declaration Button', title: 'Declare'
          %a{href: inform_path}
            = I18n.t 'home.inform'
      %div{id: 'flash'}
        %p{class: "notice"}
          = notice
        %p{class: "alert"}
          = alert
      %div{id: 'contents'}
        = yield
      %div{id: 'footer'}
        %ul
          - [:en, :fr, :jp].sort.select{|l| l != I18n.locale}.each do |l|
            %li
              %a{href: "/?locale=#{l}"}
                = l.to_s
          %li
            = link_to(I18n.t('navigation.home'), root_path)
          %li
            = link_to(I18n.t('navigation.project'), project_path)
          %li
            = link_to(I18n.t('navigation.contact'), contact_path)
          %li
            = link_to(I18n.t('navigation.disclaimer'), disclaimer_path)
          - if user_signed_in?
            %li
              = link_to(I18n.t('navigation.events'), research_events_path)
            %li
              = link_to(I18n.t('navigation.logout'), destroy_user_session_path)
          - else
            %li
              = link_to(I18n.t('navigation.login'), new_user_session_path)

app/views/partials/_footlinks.html.haml
%p
  ISAC Tokyo 2014 -
  = link_to 'en', controller: controller, action: action, locale: :en
  | 
  = link_to 'jp', controller: controller, action: action, locale: :jp
  |
  = link_to 'fr', controller: controller, action: action, locale: :fr